<a href="https://colab.research.google.com/github/PratikshaShelke24/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy

In [1]:
#import numpy
import numpy as np

In [3]:
#create one dimentioanl array
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#cretae two dimentional array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#indexing
element=arr2[1]
print(element)

[4 5 6]


In [14]:
#slicing
sub_arr=arr1[1:4]
print(sub_arr)

[2 3 4]


In [16]:
#mathmatical opreations
#sum of all numbers in array
total=np.sum(arr1)
print(total)

55


In [17]:
#mean
mean=np.mean(arr1)
print(mean)

5.5


In [18]:
#squre root
sqrt=np.sqrt(arr1)
print(sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [19]:
a=9
sqrt=np.sqrt(a)
print(sqrt)

3.0
