<a href="https://colab.research.google.com/github/PratikshaShelke24/data-science/blob/main/session3pratices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arithimetic opreation in numpy

In [2]:
#element wise
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
sum=arr1+arr2
print(sum)

[5 7 9]


In [12]:
#mathmatical functions

#sum
arr3=np.array([1,2,3,4])
total=np.sum(arr3)
print(total)

#mean
mean=np.mean(arr3)
print(mean)

#squre root
sqrt_arr=np.sqrt(9)
print(sqrt_arr)



10
2.5
3.0
3.0


In [14]:
arr4=np.array([9,4,64,81,49]) #pass array
sqrt_arr1=np.sqrt(arr4)
print(sqrt_arr1)

[3. 2. 8. 9. 7.]


In [ ]:
#Linear Algebra


In [18]:
#	Matrix multiplication
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[6,7],[8,9]])
product=np.dot(mat1,mat2)
print(product)

[[22 25]
 [50 57]]


In [19]:
#inverise of matrix
inv_matrix = np.linalg.inv(mat1)
print(inv_matrix)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
#Determinant of a matrix:

determinant = np.linalg.det(mat1)
print(determinant)


-2.0000000000000004


In [ ]:
#numpy for data science task



In [29]:
#Handling Missing Values:
arr = np.array([1, 2, 5,7, 4])
print(np.isnan(arr))


[False False False False False]


In [26]:
#reshape
arr_reshaped = arr.reshape(2, 2)  # Reshape a 1D array to 2D
print(arr_reshaped)


[[1 2]
 [5 4]]


In [ ]:
#Statistical Analysis

In [30]:
#Variance
variance = np.var(arr)
print(variance)


4.5600000000000005


In [31]:
#Standard Deviation
std_dev = np.std(arr)
print(std_dev)


2.1354156504062622
